marvelapi/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$',views.Home.as_view(),name="main"),
	url(r'^(?P<id>[0-9]+)/$',views.DetailView.as_view(),name='detalle')
]

marvelapi/marvelapi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from main import urls as urlsMain
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include(urlsMain, namespace="main")),
    url(
    	regex=r'^media/(?P<path>.*)$',
    	view=serve,
    	kwargs={'document_root':settings.MEDIA_ROOT}
    	)
]

marvelapi/main/models.py
from django.db import models

class Heroe(models.Model):
	nombre=models.CharField(max_length=100)
	historia=models.TextField()
	poder=models.CharField(max_length=100)
	imagen=models.ImageField(upload_to='images')

	def __str__(self):
		return self.nombre

marvelapi/main/views.py
from django.shortcuts import render
from .models import Heroe
from django.views.generic import View

class Home(View):
	def get(self,request):
		heroe=Heroe.objects.all()
		template_name='main.html'
		context={
		'heroes':heroe
		}

		return render(request,template_name,context)

class DetailView(View):
	def get(self,request,id):
		template_name="detalle.html"
		heroe=Heroe.objects.get(id=id)
		context={
		'heroe':heroe
		}

		return render(request,template_name,context)

marvelapi/main/templates/detalle.html
<!DOCTYPE html>
<html>
<head>
	<title></title>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<div class="panel panel-default">
					<div class="panel-heading">{{heroe.nombre}}</div>
				  	<div class="panel-body">
				  		<div class="col-sm-6">
				  			<p>{{heroe.historia}}</p>
							<p>{{heroe.poder}}</p>	
				  		</div>
				  		<div class="col-sm-6">
							<img src="/media/{{heroe.imagen}}" class='img-responsive img-rounded'>  				
				  		</div>
				  	</div>
				</div>
			</div>
		</div>
</body>
</html>

marvelapi/main/templates/main.html
<!DOCTYPE html>
<html>
<head>
	
	<title>Proyecto Main</title>
	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
	<section class="container">
	{%for heroe in heroes%}
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">
				<div class="panel panel-default">
					<div class="panel-heading">{{heroe.nombre}}</div>
				  	<div class="panel-body">
				  		<div class="col-sm-6">
				  			<p>{{heroe.historia}}</p>
							<p>{{heroe.poder}}</p>	
							<a href="{% url 'main:detalle' heroe.id %}">Detalles</a>
				  		</div>
				  		<div class="col-sm-6">
							<img src="/media/{{heroe.imagen}}" class='img-responsive img-rounded'>  		
				  		</div>
				  	</div>
				</div>
			</div>
		</div>
	{%empty%}
		<h1>I need a hero!!</h1>
	{%endfor%}
	</section>
</body>
</html>